### ISSUE TITLE
Error in split.default(x = cells.vector, f = ceiling(x = seq_along(along.with = cells.vector)/ncells)) :

### ISSUE THREAD

**Issue by NicolaasVanRenne** [digitalcytometry/cytospace#106]
Hi,

I got an error probably related to get_cellfracs_seuratv3 

> Error in split.default(x = cells.vector, f = ceiling(x = seq_along(along.with = cells.vector)/ncells)) :

It even occurs when running the provided example data. 

Is there any way to solve this?

this was also mentioned by @26huangxu on  https://github.com/digitalcytometry/cytospace/issues/97

Below is what I run.

cytospace \
> -sp brca_scRNA_GEP.txt \
> -ctp brca_scRNA_celllabels.txt \
> -stp brca_STdata_GEP.txt  \
> -cp brca_STdata_coordinates.txt

Read and validate data ...
100% |██████████████████████████████████████████████████| Reading data [done]
Estimating cell type fractions
2024-11-05 17:22:07.39464 Load ST data
Warning: Data is of class matrix. Coercing to dgCMatrix.
Error in split.default(x = cells.vector, f = ceiling(x = seq_along(along.with = cells.vector)/ncells)) :
  group length is 0 but data length > 0
Calls: get_cellfracs_seuratv3 ... SCTransform -> SCTransform.StdAssay -> split -> split.default
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
Traceback (most recent call last):
  File "/home/nicolaas/anaconda3/envs/cytospace_v1.1.0/bin/cytospace", line 8, in <module>
    sys.exit(run_cytospace())
  File "/home/nicolaas/anaconda3/envs/cytospace_v1.1.0/lib/python3.9/site-packages/cytospace/cytospace.py", line 713, in run_cytospace
    main_cytospace(**arguments)
  File "/home/nicolaas/anaconda3/envs/cytospace_v1.1.0/lib/python3.9/site-packages/cytospace/cytospace.py", line 526, in main_cytospace
    read_data(scRNA_path, cell_type_path,
  File "/home/nicolaas/anaconda3/envs/cytospace_v1.1.0/lib/python3.9/site-packages/cytospace/cytospace.py", line 39, in read_data
    cell_type_fraction_estimation_path = estimate_cell_type_fractions(scRNA_path, cell_type_path, st_path, output_path, output_prefix)
  File "/home/nicolaas/anaconda3/envs/cytospace_v1.1.0/lib/python3.9/site-packages/cytospace/common/common.py", line 137, in estimate_cell_type_fractions
    out = subprocess.run(run_args, check=True)
  File "/home/nicolaas/anaconda3/envs/cytospace_v1.1.0/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '/home/nicolaas/anaconda3/envs/cytospace_v1.1.0/lib/python3.9/site-packages/cytospace/get_cellfracs_seuratv3.R', '--scrna-path', 'brca_scRNA_GEP.txt', '--ct-path', 'brca_scRNA_celllabels.txt', '--st-path', 'brca_STdata_GEP.txt', '--outdir', '/cytospace_results', '--prefix', '']' returned non-zero exit status 1.

**Comment by NicolaasVanRenne** [comment]
Never mind, I installed it with the .yml file into a conda environment and it works. Probably will have to do with the Seurat5 that I was using that has a different data structure than seurat v3
