### ISSUE TITLE
Seurat_weights.txt does not exist

### ISSUE THREAD

**Issue by williamsdrake** [digitalcytometry/cytospace#53]
Hi,

I'd like to try using this tool, but am getting the following error(s). I've used the tools you provided to get the relevant sc and st info from seurat objects. At least one of the issues is Seurat_weights.txt is not being generated, but unsure of why it's failing. Any help would be appreciated

```
(cytospace) C:\Users\cytospace>  cytospace -sp seuratData\scRNA_data.txt -ctp seuratData\cell_type_labels.txt -stp seuratData\B_ST_data.txt -cp seuratData\B_Coordinates.txt -o cytospace_results -sm lap_CSPR
Read and validate data ...
100% |██████████████████████████████████████████████████| Reading data [done]
Estimating cell type fractions
  File "<stdin>", line 24
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
Warning message:
In if (grepl("^\\{|^\\[", output)) { :
  the condition has length > 1 and only the first element will be used
100% |██████████████████████████████████████████████████| Reading data [done]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\site-packages\cytospace\common\common.py", line 18, in read_file
    file_data = dt.fread(file_path)
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\site-packages\datatable\utils\fread.py", line 122, in _resolve_source_any
    return _resolve_source_file(src, tempfiles)
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\site-packages\datatable\utils\fread.py", line 199, in _resolve_source_file
    raise ValueError("File %s`%s` does not exist"
datatable.exceptions.ValueError: File C:\Users\cytospace\cytospace_results\Seurat_weights.txt does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\cytospace\Scripts\cytospace.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\site-packages\cytospace\cytospace.py", line 691, in run_cytospace
    main_cytospace(**arguments)
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\site-packages\cytospace\cytospace.py", line 528, in main_cytospace
    read_data(scRNA_path, cell_type_path,
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\site-packages\cytospace\cytospace.py", line 64, in read_data
    cell_type_fraction_data = read_file(cell_type_fraction_estimation_path)
  File "C:\ProgramData\Anaconda3\envs\cytospace\lib\site-packages\cytospace\common\common.py", line 24, in read_file
    raise IOError("Make sure you provided the correct path to input files. "
OSError: Make sure you provided the correct path to input files. The following input file formats are supported: .csv with comma ',' as delimiter, .txt or .tsv with tab '\t' as delimiter.
```

**Comment by hsjeon-k** [comment]
Hello, thank you for letting us know!

It seems that this might be occurring due to how system paths are defined in Windows. We will update the code soon to account for this, and follow up on this thread once it is updated.

Once again, thank you for alerting us to this issue!

**Comment by hsjeon-k** [comment]
Hi, this issue should have been resolved with today's update. Please update your local installation through the "Updating local installations" part of the documentation, and please let us know if you encounter any further issues!
