### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by DHGK** [digitalcytometry/cytospace#67]
Hello! Thank you for sharing this package. While I was hoping to give it a try on our datasets, I have encountered some issues that I wonder if anyone may have an idea how to solve. I have successfully installed cytospace, but when I tried the following line, I got an error that I'm not sure how to interpret:

```
(cytospace) mac-pro:cytospace labadmin$ cytospace -scRNA-path ~/Desktop/expressionSC.txt -cell-type-path ~/Desktop/celltypeSC.txt -st-path ~/Desktop/expressionST.txt -coordinates-path ~/Desktop/coordinateST.txt -o cytospace_results
```
```
Traceback (most recent call last):

  File "/Users/labadmin/opt/anaconda3/envs/cytospace/bin/cytospace", line 5, in <module>

    from cytospace.cytospace import run_cytospace

  File "/Users/labadmin/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/__init__.py", line 1, in <module>

    from .cytospace import *

  File "/Users/labadmin/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 13, in <module>

    from cytospace.linear_assignment_solvers import (calculate_cost, match_solution, import_solver,

  File "/Users/labadmin/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/linear_assignment_solvers/__init__.py", line 1, in <module>

    from .linear_assignment_solvers import *

  File "/Users/labadmin/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/linear_assignment_solvers/linear_assignment_solvers.py", line 5, in <module>

    from ortools.graph import pywrapgraph

  File "/Users/labadmin/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/ortools/graph/pywrapgraph.py", line 13, in <module>

    from . import _pywrapgraph

ImportError: dlopen(/Users/labadmin/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/ortools/graph/_pywrapgraph.so, 2): Symbol not found: ____chkstk_darwin

  Referenced from: /Users/labadmin/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/ortools/graph/../../ortools/.libs/libortools.dylib (which was built for Mac OS X 10.15)

  Expected in: /usr/lib/libSystem.B.dylib

 in /Users/labadmin/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/ortools/graph/../../ortools/.libs/libortools.dylib

```

**Comment by hsjeon-k** [comment]
Hello, thank you for letting us know!

It looks like the issue might be related to your macOS version compatibility with one of the external libraries being imported (ortools v9.2.9972), which I think might be supporting 10.15 (Catalina) or above based on the error message. Could you let us know which version of macOS you are using? This can be found by clicking on the Apple logo on the top left - "About This Mac".

**Comment by DHGK** [comment]
Thank you for your reply, @hsjeon-k. I was using 10.13.6  High Sierra. 

I also tried running on my personal laptop (macOS 12.6 Monterey with M1 chip). Unfortunately, I didn't get a success either and the error seemed to be the `lapjav` package.

```
Traceback (most recent call last):

  File "/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/linear_assignment_solvers/linear_assignment_solvers.py", line 16, in import_solver

    from lapjv import lapjv

ModuleNotFoundError: No module named 'lapjv'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/opt/anaconda3/envs/cytospace/bin/cytospace", line 8, in <module>

    sys.exit(run_cytospace())

  File "/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 683, in run_cytospace

    main_cytospace(**arguments)

  File "/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 511, in main_cytospace

    solver = import_solver(solver_method)

  File "/opt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/linear_assignment_solvers/linear_assignment_solvers.py", line 23, in import_solver

    raise ModuleNotFoundError("The Python package containing the solver_method option "

ModuleNotFoundError: The Python package containing the solver_method option you have chosen lapjv was not found. If you selected 'lapjv_compat' solver, install package 'lap'by running 'pip install lap==0.4.0'. If you selected 'lapjv'solver, install package 'lapjv' by running `pip install lapjv==1.3.14'or check the package home page for further instructions.
```

**Comment by DHGK** [comment]
Thank you, @hsjeon-k ! It works now.
