### ISSUE TITLE
error, but I do not know why

### ISSUE THREAD

**Issue by Yulintian** [digitalcytometry/cytospace#85]
2023-09-07 02:39:26 Load scRNA data
Error in vst(method = "glmGamPoi", umi = new("dgCMatrix", i = c(2L, 17L,  :
  Please install the glmGamPoi package. See https://github.com/const-ae/glmGamPoi for details.
Calls: get_cellfracs_seuratv3 -> %>% -> RunPCA -> SCTransform -> do.call -> vst
Execution halted
Traceback (most recent call last):
  File "/home/ylt/anaconda3/envs/cytospace/bin/cytospace", line 8, in <module>
    sys.exit(run_cytospace())
  File "/home/ylt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 690, in run_cytospace
    main_cytospace(**arguments)
  File "/home/ylt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 522, in main_cytospace
    read_data(scRNA_path, cell_type_path,
  File "/home/ylt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 35, in read_data
    cell_type_fraction_estimation_path = estimate_cell_type_fractions(scRNA_path, cell_type_path, st_path, output_path, output_prefix)
  File "/home/ylt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/common/common.py", line 119, in estimate_cell_type_fractions
    out = subprocess.run(run_args, check=True)
  File "/home/ylt/anaconda3/envs/cytospace/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '/home/ylt/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/get_cellfracs_seuratv3.R', '--scrna-path', '/home/ylt/workshop/Ten/scRNA_data.txt', '--ct-path', '/home/ylt/workshop/Ten/cell_type_labels.txt', '--st-path', '/home/ylt/workshop/Ten/ST_data.txt', '--outdir', '/home/ylt/cytospace_results', '--prefix', '']' returned non-zero exit status 1.

**Comment by WubingZhang** [comment]
Please install the glmGamPoi package in the environment and repeat it.

Best,
Wubing

**Comment by Yulintian** [comment]
Thanks,
I have try the old version, and no error report.&nbsp;
So I just used the cytospace -1.0.3 version.


Thank you again
Best regard,


Yu Lintian






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "digitalcytometry/cytospace"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月7日(星期四) 上午7:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [digitalcytometry/cytospace] error, but I do not know why (Issue #85)





 
Please install the glmGamPoi package in the environment and repeat it.
 
Best,
 Wubing
