### ISSUE TITLE
Error running cytoSPACE. glmGamPoi

### ISSUE THREAD

**Issue by alfonsosaera** [digitalcytometry/cytospace#95]
Today (24th of November 2023) I installed cytospace with the following commands. No errors

```
git clone https://github.com/digitalcytometry/cytospace
cd cytospace
conda env create -f environment.yml
conda activate cytospace
pip install .
pip install lapjv==1.3.14
```

When running cytoscape the command
```
conda activate cytoscape
cytospace \
   --scRNA-path ${scRefPath}/scRNA_GEP.txt \
   --cell-type-path ${scRefPath}/scRNA_celllabels.txt \
   --st-path visium_STdata_GEP.txt' \
   --coordinates-path visium_STdata_coordinates.txt'
```
but I got the following error

```
Read and validate data ...
100% |██████████████████████████████████████████████████| Reading data [done]
Estimating cell type fractions
2023-11-24 12:12:36 Load ST data
PC_ 1 
Positive:  ENSG00000197971, ENSG00000123560, ENSG00000091513, ENSG00000204655, ENSG00000109846, ENSG00000118785, ENSG00000173786, ENSG00000160307, ENSG00000105695, ENSG00000112531 
	   ENSG00000107331, ENSG00000099194, ENSG00000168314, ENSG00000167123, ENSG00000184144, ENSG00000013297, ENSG00000172508, ENSG00000250722, ENSG00000080822, ENSG00000107317 
	   ENSG00000078804, ENSG00000019144, ENSG00000167996, ENSG00000124920, ENSG00000125247, ENSG00000167641, ENSG00000160781, ENSG00000136960, ENSG00000054690, ENSG00000148180 
Negative:  ENSG00000132639, ENSG00000154146, ENSG00000277586, ENSG00000154277, ENSG00000163032, ENSG00000101210, ENSG00000120885, ENSG00000020129, ENSG00000160014, ENSG00000074317 
	   ENSG00000131711, ENSG00000104722, ENSG00000128245, ENSG00000170027, ENSG00000189241, ENSG00000130558, ENSG00000171617, ENSG00000104888, ENSG00000070808, ENSG00000166681 
	   ENSG00000188191, ENSG00000110436, ENSG00000145920, ENSG00000128656, ENSG00000103034, ENSG00000166165, ENSG00000139970, ENSG00000104435, ENSG00000157782, ENSG00000173267 
PC_ 2 
Positive:  ENSG00000132639, ENSG00000131711, ENSG00000104722, ENSG00000123560, ENSG00000277586, ENSG00000197971, ENSG00000154146, ENSG00000154277, ENSG00000173267, ENSG00000100285 
	   ENSG00000104435, ENSG00000080824, ENSG00000204655, ENSG00000091513, ENSG00000100604, ENSG00000173786, ENSG00000183036, ENSG00000170027, ENSG00000167123, ENSG00000171724 
	   ENSG00000143153, ENSG00000105695, ENSG00000109971, ENSG00000103316, ENSG00000104888, ENSG00000143858, ENSG00000142634, ENSG00000145335, ENSG00000165023, ENSG00000139190 
Negative:  ENSG00000131095, ENSG00000110436, ENSG00000079215, ENSG00000135821, ENSG00000145824, ENSG00000115756, ENSG00000129244, ENSG00000134817, ENSG00000198944, ENSG00000142089 
	   ENSG00000101439, ENSG00000113140, ENSG00000018625, ENSG00000133048, ENSG00000171885, ENSG00000117525, ENSG00000168309, ENSG00000196136, ENSG00000130203, ENSG00000185201 
	   ENSG00000135744, ENSG00000181418, ENSG00000026025, ENSG00000134769, ENSG00000205336, ENSG00000182103, ENSG00000070808, ENSG00000162545, ENSG00000168710, ENSG00000106624 
PC_ 3 
Positive:  ENSG00000104722, ENSG00000173267, ENSG00000100285, ENSG00000277586, ENSG00000133048, ENSG00000109107, ENSG00000143858, ENSG00000131711, ENSG00000183036, ENSG00000100362 
	   ENSG00000139190, ENSG00000131095, ENSG00000105711, ENSG00000171724, ENSG00000103316, ENSG00000135821, ENSG00000104435, ENSG00000142089, ENSG00000163453, ENSG00000080824 
	   ENSG00000100604, ENSG00000110436, ENSG00000196136, ENSG00000079215, ENSG00000184113, ENSG00000142634, ENSG00000120885, ENSG00000134769, ENSG00000107317, ENSG00000198963 
Negative:  ENSG00000115756, ENSG00000120049, ENSG00000171617, ENSG00000020129, ENSG00000198944, ENSG00000187094, ENSG00000070808, ENSG00000105696, ENSG00000186469, ENSG00000128989 
	   ENSG00000136099, ENSG00000135426, ENSG00000126583, ENSG00000162545, ENSG00000105376, ENSG00000004660, ENSG00000178394, ENSG00000164326, ENSG00000137825, ENSG00000066248 
	   ENSG00000221890, ENSG00000113319, ENSG00000176956, ENSG00000178531, ENSG00000168490, ENSG00000070961, ENSG00000120899, ENSG00000181418, ENSG00000099308, ENSG00000105290 
PC_ 4 
Positive:  ENSG00000133048, ENSG00000120885, ENSG00000131095, ENSG00000110436, ENSG00000135821, ENSG00000079215, ENSG00000171885, ENSG00000196136, ENSG00000107317, ENSG00000129244 
	   ENSG00000117525, ENSG00000134769, ENSG00000018625, ENSG00000109472, ENSG00000134817, ENSG00000135744, ENSG00000168710, ENSG00000144749, ENSG00000240583, ENSG00000026508 
	   ENSG00000132470, ENSG00000143772, ENSG00000167191, ENSG00000148053, ENSG00000124145, ENSG00000170075, ENSG00000113916, ENSG00000117519, ENSG00000144908, ENSG00000151914 
Negative:  ENSG00000154734, ENSG00000163638, ENSG00000187498, ENSG00000184489, ENSG00000184113, ENSG00000102265, ENSG00000141753, ENSG00000149591, ENSG00000101335, ENSG00000198467 
	   ENSG00000189058, ENSG00000198959, ENSG00000011465, ENSG00000158859, ENSG00000187479, ENSG00000103196, ENSG00000107796, ENSG00000137801, ENSG00000000971, ENSG00000165949 
	   ENSG00000110799, ENSG00000137558, ENSG00000163453, ENSG00000120129, ENSG00000113721, ENSG00000117394, ENSG00000166710, ENSG00000122786, ENSG00000138061, ENSG00000115414 
PC_ 5 
Positive:  ENSG00000100362, ENSG00000136099, ENSG00000128683, ENSG00000173267, ENSG00000157103, ENSG00000109107, ENSG00000170419, ENSG00000166165, ENSG00000100285, ENSG00000110436 
	   ENSG00000145824, ENSG00000139190, ENSG00000111249, ENSG00000105711, ENSG00000143858, ENSG00000164326, ENSG00000187730, ENSG00000227051, ENSG00000163888, ENSG00000170091 
	   ENSG00000104722, ENSG00000277586, ENSG00000143153, ENSG00000148798, ENSG00000187664, ENSG00000132821, ENSG00000128564, ENSG00000107331, ENSG00000165795, ENSG00000101438 
Negative:  ENSG00000163630, ENSG00000165023, ENSG00000153234, ENSG00000131095, ENSG00000182601, ENSG00000169032, ENSG00000162630, ENSG00000104888, ENSG00000145920, ENSG00000171246 
	   ENSG00000142634, ENSG00000197971, ENSG00000176956, ENSG00000122585, ENSG00000048540, ENSG00000128656, ENSG00000196358, ENSG00000170381, ENSG00000145335, ENSG00000158258 
	   ENSG00000271824, ENSG00000172575, ENSG00000026508, ENSG00000240583, ENSG00000064886, ENSG00000154027, ENSG00000186469, ENSG00000132639, ENSG00000128989, ENSG00000196136 
2023-11-24 12:14:25 Load scRNA data
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Error in vst(method = "glmGamPoi", umi = new("dgCMatrix", i = c(20L, 39L,  : 
  Please install the glmGamPoi package. See https://github.com/const-ae/glmGamPoi for details.
Calls: get_cellfracs_seuratv3 -> %>% -> RunPCA -> SCTransform -> do.call -> vst
Además: Warning message:
In get_cellfracs_seuratv3(sc_path = args$scrna_path, ct_path = args$ct_path,  :
  Downsampling to 10000 cells with equal number of cells for each cell type, for the purposes of cell type fraction estimation only. This will not affect the dataset in the main CytoSPACE run. To disable downsampling, please run get_cellfracs_seuratv3.R separately with the --disable-fraction-downsampling flag specified. The output file [prefix]Seurat_weights.txt can then be passed to CytoSPACE with the -ctfep flag.
Ejecución interrumpida
Traceback (most recent call last):
  File "/home/asaera/miniconda3/envs/cytospace/bin/cytospace", line 8, in <module>
    sys.exit(run_cytospace())
  File "/home/asaera/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 690, in run_cytospace
    main_cytospace(**arguments)
  File "/home/asaera/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 522, in main_cytospace
    read_data(scRNA_path, cell_type_path, 
  File "/home/asaera/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 35, in read_data
    cell_type_fraction_estimation_path = estimate_cell_type_fractions(scRNA_path, cell_type_path, st_path, output_path, output_prefix)
  File "/home/asaera/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/common/common.py", line 119, in estimate_cell_type_fractions
    out = subprocess.run(run_args, check=True)
  File "/home/asaera/miniconda3/envs/cytospace/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '/home/asaera/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/get_cellfracs_seuratv3.R', '--scrna-path', '/media/sequentia/isilon/consultoria/M-E230021_B230021_Carmen/scRNAseq_datasets/human/human.control_GEP.txt', '--ct-path', '/media/sequentia/isilon/consultoria/M-E230021_B230021_Carmen/scRNAseq_datasets/human/human.control_celllabels.txt', '--st-path', 'human.10-023_STdata_GEP.txt', '--outdir', '/media/sequentia/isilon/consultoria/M-E230021_B230021_Carmen/results/human/10-023/cytoSpace/cytospace_results', '--prefix', '']' returned non-zero exit status 1.
```

Following the advice of another issue post I tried to install glmGamPoi  with the command

```conda install -c bioconda bioconductor-glmgampoi```

but got this error

```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package zlib conflicts for:
python=3.8 -> sqlite[version='>=3.41.2,<4.0a0'] -> zlib[version='>=1.2.13,<2.0a0']
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0']

Package libzlib conflicts for:
python=3.8 -> zlib[version='>=1.2.13,<1.3.0a0'] -> libzlib==1.2.13=hd590300_5
python=3.8 -> libzlib[version='>=1.2.13,<1.3.0a0']

Package libstdcxx-ng conflicts for:
python=3.8 -> libffi[version='>=3.2.1,<3.3a0'] -> libstdcxx-ng[version='>=7.2.0']
python=3.8 -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=7.3.0']

Package ncurses conflicts for:
python=3.8 -> readline[version='>=7.0,<8.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0']
python=3.8 -> ncurses[version='>=6.1,<7.0a0|>=6.2,<7.0a0|>=6.3,<7.0a0|>=6.4,<7.0a0']

Package libgcc-ng conflicts for:
python=3.8 -> libffi[version='>=3.4,<4.0a0'] -> libgcc-ng[version='>=7.2.0|>=9.4.0']
python=3.8 -> libgcc-ng[version='>=11.2.0|>=12|>=7.5.0|>=7.3.0']

Package openssl conflicts for:
python=3.8 -> openssl[version='>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1u,<1.1.2a|>=1.1.1v,<1.1.2a|>=3.0.10,<4.0a0|>=3.1.3,<4.0a0|>=3.0.9,<4.0a0|>=3.0.8,<4.0a0']
bioconductor-glmgampoi -> bioconductor-hdf5array[version='>=1.26.0,<1.27.0'] -> openssl[version='>=1.1.1l,<1.1.2a|>=1.1.1s,<1.1.2a|>=3.1.0,<4.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0
  - bioconductor-glmgampoi -> r-rcpp -> __glibc[version='>=2.17|>=2.17,<3.0.a0']

Your installed version is: 2.27
```

I also tried to install the package opening an R terminal within the environment following the bioconductor instructions
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("glmGamPoi")
```
but I get a lot of errors installing in both BiocManager and glmGamPoi installations.

How can I do to install and run cytoSPACE?

thanks

Alfonso

**Comment by erinlbrown** [comment]
Hi Alfonso,

It seems this is causing problems for others as well. We will aim to address this as part of the next release. For now, one thing you could try is removing your current CytoSPACE conda environment, updating the environment.yml file to add the line  ` - bioconductor-glmgampoi` under dependencies, then reinstalling. If you try this, it would be helpful to know if it works for you as I have had difficulty replicating the environment issue you and others are reporting.

If that does not work, there are some other options as well:
- You could install an older release of CytoSPACE instead (v1.0.4), which does not require this package but also lacks sparse matrix support
- If you need the sparse matrix support, you could update your local installation of the current version (v1.0.5) to remove the method specification from the SCTransform() call on line 65 of get_cellfracs_seuratv3.R

Best,
Erin

**Comment by shawnfan19** [comment]
hello erin, 

i had the same issue. updating ```environment.yml``` with ```- bioconductor-glmgampoi``` under dependencies solved it. thank you 

shawn

**Comment by erinlbrown** [comment]
Thank you, Shawn! That's great--I'll update the current version with this fix.
